### GET all Characters

GET http://localhost:3000/api/characters HTTP/1.1

### GET a single Character

GET http://localhost:3000/api/characters/Rachel HTTP/1.1

### DELETE a Character

GET http://localhost:3000/api/characters/Monica HTTP/1.1

### POST a Character

GET http://localhost:3000/api/characters HTTP/1.1
Content-Type: application/json

{
    "name": "Chandler",
    "last-name":"Bing",
    "actor": "Matthew Perry"
}